#!/usr/bin/env ruby

begin
  require './config/environment.rb'
  puts "Detected rails app has been loaded."
rescue LoadError
end

require 'ruby-clock'
require 'method_source'

class Rufus::Scheduler::Job
  def identifier
    @identifier ||= begin
      name || handler.source.split("\n").reject(&:empty?).grep_v(/#.*/)[-2].strip
    rescue
      begin
        source_location.join('-')
      rescue
        'error-calculating-job-identifier'
      end
    end
  end
end

include RubyClock

listen_to_signals
prepare_rake
schedule.pause

load ARGV[0] || 'Clockfile'

if defined?(::Rails)
  schedule.instance_eval do
    @old_around_trigger = method :around_trigger
    def around_trigger(job)
      ::Rails.application.reloader.wrap do
        @old_around_trigger.call(job){ yield }
      end
    end
  end
end

run_jobs
