#!/usr/bin/env ruby

begin
  require './config/environment.rb'
  puts "Detected rails app has been loaded."
rescue LoadError
end

require 'ruby-clock'
require 'method_source'

class Rufus::Scheduler::Job
  def identifier
    @identifier ||= begin
      name || handler.source.split("\n").reject(&:empty?).grep_v(/#.*/)[-2].strip
    rescue
      begin
        source_location.join('-')
      rescue
        'error-calculating-job-identifier'
      end
    end
  end
end

RubyClock.instance.listen_to_signals
RubyClock.instance.prepare_rake
RubyClock.instance.schedule.pause

load ARGV[0] || 'Clockfile'

if defined?(::Rails)
  around_action do |job_proc|
    ::Rails.application.reloader.wrap do
      job_proc.call
    end
  end
end

RubyClock.instance.freeze_around_actions

RubyClock.instance.run_jobs
